#Stage1
FROM node:16-alpine as builder
WORKDIR /app
COPY package.json .
RUN yarn install
COPY . .
RUN yarn build

FROM nginx:1.19.0
COPY ./default.conf /etc/nginx/conf.d/default.conf
WORKDIR /var/www/html/
COPY --from=builder /app/build .
ENTRYPOINT [ "nginx", "-g", "daemon off;" ]
